# Generated by Django 4.2.28 on 2026-03-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zoo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animal",
            options={"ordering": ["cost"]},
        ),
    ]
